server:
  port: 8099
  servlet:
    context-path: /identity

spring:
  application:
    name: bs-identity

  datasource:
    url: "jdbc:mysql://localhost:3306/box-stream"
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework.web: ERROR
    com.boxstream.bs_identity: DEBUG

jwt:
  signerKey: "EBw5PUxLRUlYDvWxh9SbbdCbtGshPPgoPDKfy9Sd/Qeu5G3lHox+lEsJ//ZDjvaf"
  valid-duration: 3600 # 1h- time life of an token
  refreshable-duration: 36000 # 10h - time that a token can be refreshed

