server:
  port: 8099
  servlet:
    context-path: /identity

spring:
  application:
    name: bs-identity

  datasource:
    url: "jdbc:mysql://localhost:3306/box-stream"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true